version: 2

project_name: teleskopio

dist: build-artifacts

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm
      - arm64
      - amd64
    goarm:
      - 6
      - 7
before:
  hooks:
    - make build-frontend

homebrew_casks:
  - name: teleskopio
    binary: teleskopio
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Casks
    caveats: "teleskopio --config=config.yaml"
    homepage: "https://github.com/roman-kiselenko/teleskopio"
    description: "teleskopio is an open-source small and beautiful Web Kubernetes client."
    skip_upload: true
    repository:
      owner: roman-kiselenko
      name: homebrew-teleskopio
      branch: master
