version: 2

project_name: teleskopio

dist: build-artifacts

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm
      - arm64
      - amd64
    goarm:
      - 6
      - 7
before:
  hooks:
    - make build-frontend
