name: "Lint"

on: [push, pull_request]
jobs:
  lint-backend:
    name: Lint backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Install dependencies
        run: cd frontend && pnpm install
      - name: Build frontend
        run: make build-frontend
      - name: Lint
        run: make lint
      - name: Test
        run: make test
  lint-frontend:
    name: Lint frontend
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - name: Install dependencies
        run: cd frontend && pnpm install

      - name: Run ESLint
        working-directory: ./frontend
        run: pnpm run lint
